# Generated by Django 4.2 on 2023-04-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='phone_number',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
    ]
