# Generated by Django 4.2 on 2023-04-29 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('debts', '0004_remove_debt_creditor_remove_debt_debtor'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='creditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_debts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debt',
            name='debtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debit_debts', to=settings.AUTH_USER_MODEL),
        ),
    ]
