# Generated by Django 4.2 on 2023-05-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0005_alter_transaction_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('borrow', 'Взять в долг'), ('repay', 'Погасить займ'), ('lend', 'Дать в долг'), ('receive', 'Принять погашение')], default='borrow', max_length=20, verbose_name='Transaction type'),
        ),
    ]
