# Generated by Django 4.2 on 2023-04-29 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0006_alter_debt_creditor_alter_debt_debtor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='creditor',
        ),
        migrations.RemoveField(
            model_name='debt',
            name='debtor',
        ),
    ]
