# Generated by Django 4.2 on 2023-04-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0007_remove_debt_creditor_remove_debt_debtor'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='tranzaction_type',
            field=models.CharField(choices=[('ВЗЯТЬ', 'Взять'), ('ДАТЬ', 'Дать')], default='ВЗЯТЬ', max_length=20, verbose_name='Tranzaction type'),
        ),
    ]
