# Generated by Django 4.2 on 2023-04-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0008_debt_tranzaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='tranzaction_type',
            field=models.CharField(choices=[('Взял в долг', 'Взять'), ('Дал в долг', 'Дать')], default='ВЗЯТЬ', max_length=20, verbose_name='Tranzaction type'),
        ),
    ]
