# Generated by Django 4.2 on 2023-05-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0010_tranzaction_rename_agent_contact_delete_debt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tranzaction',
            name='tranzaction_type',
            field=models.CharField(choices=[('Займ', 'Займ'), ('Долг', 'Долг')], default='Займ', max_length=20, verbose_name='Tranzaction type'),
        ),
    ]
