# Generated by Django 4.2 on 2023-05-05 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0011_tranzaction_tranzaction_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tranzaction',
            old_name='tranzaction_type',
            new_name='type',
        ),
    ]
