# Generated by Django 4.2 on 2023-05-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0012_rename_tranzaction_type_tranzaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tranzaction',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='Publish'),
        ),
    ]
